config/routes.rb
Rails.application.routes.draw do

  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'brad', password: '1234', only: [:destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'This is the about page'
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  http_basic_authenticate_with name: 'brad', password: '1234', except: %i[index show]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      # redirect_to new_post_path
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="card bg-light">
        <div class="card-body">
            <p><strong><%= comment.username %></strong>: <%= comment.body %>
            <%= link_to "[X]", [comment.post, comment], method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
            </p>
        </div>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-default'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">SimpleBlog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item nav-link"><%= link_to "Home", home_path %></li>
          <li class="nav-item nav-link"><%= link_to "Create Post", new_post_path %></li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>    

    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
    <div class="card bg-light">
        <div class="card-body">
            <h3><%= post.title %></h3>
            <p><%= post.body %></p>
            <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
        </div>
    </div>
    <br>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>    

    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), data: {confirm: 'Are you sure that you wana edit?'}, :class => 'btn btn-warning' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
<hr>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>